services:
  admin:
    build:
      context: .
      dockerfile: ./projects/Admin/Containerfile
    ports:
      - "31112:31112"
    environment:
    depends_on:
      - backend
    network_mode: host

  backend:
    build:
      context: .
      dockerfile: ./projects/Backend/Containerfile
    ports:
      - "31111:31111"
    environment:
      API_SERVER_HOST: "0.0.0.0"
      API_SERVER_PORT: 31111
    network_mode: host
