services:
  admin:
    build:
      context: .
      dockerfile: ./projects/Admin/Containerfile
      args:
        GIT_HASH: ${GIT_COMMIT_HASH}
        API_SERVER_URL: "http://localhost:31111"
        PUBLIC_APP_URL: "http://localhost:31113"
        BASE_PATH: "/admin"
    ports:
      - "31112:31112"
    depends_on:
      - backend
    network_mode: host    # Should ditch host network mode and use bridge mode instead
                          # But I have to find a way to get rid of errors of CNI network automatically created by podman-compose

  public:
    build:
      context: .
      dockerfile: ./projects/Public/Containerfile
      args:
        GIT_HASH: ${GIT_COMMIT_HASH}
        API_SERVER_URL: "http://localhost:31111"
        BASE_PATH: "/"
    ports:
      - "31113:31113"
    depends_on:
      - backend
    network_mode: host

  backend:
    build:
      context: .
      dockerfile: ./projects/Backend/Containerfile
    ports:
      - "31111:31111"
    environment:
      JWT_SECRET: som_myboothmanager_ni
      SUPERADMIN_ID: admin
      SUPERADMIN_PASS: should1be2changed!
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: myboothmanager
      SEQUELIZE_TIMEZONE: +09:00
    network_mode: host
