name: Build Node.js project and deploy to branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy
        uses: EndBug/add-and-commit@v9
        with:
          add: "./dist --force"
          default_author: github_actions
          message: "Deploy"
          new_branch: "deploy"
