name: Node.js

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        node-version: [ "18.x", "lts/*", "*" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Initialize
        run: pnpm install --frozen-lockfile && pnpm common:build
      - name: Do test
        run: pnpm test
