name: Node.js

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        node-version: [ "18.x", "lts/*", "*" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Pre setup
        run: yarn pre
      - name: Do test
        run: yarn test
